version: "3.8"

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend-dist:/srv/frontend-dist
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - barber-shop-network

volumes:
  caddy_data:
  caddy_config:

networks:
  barber-shop-network:
    external: true
