name: Deploy Backend to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3

      - name: Clone backend repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git clone https://x-access-token:$GH_TOKEN@github.com/stevenjwiltse/api-deploy.git backend

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t backend-app .

      - name: Save Docker image to file
        run: docker save backend-app | gzip > backend-app.tar.gz

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend-app.tar.gz"
          target: "~/"

      - name: Run docker-compose on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/api-deploy
            docker-compose down
            docker-compose up -d --build
