name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout barbershop-deploy
        uses: actions/checkout@v3

      - name: Clone Frontend Repo
        run: git clone https://github.com/stevenjwiltse/ui-deploy.git frontend

      - name: Build Frontend Locally
        run: |
          cd frontend
          npm install
          npm run build
          mkdir -p frontend/frontend-dist
          cp -r dist/* frontend/frontend-dist/

      - name: Copy Built Frontend to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend"
          target: "~/ui-deploy"

      - name: SSH into EC2 and Run Full Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash ~/barbershop-deploy/deploy/deploy-all.sh
