name: Deploy Full Stack

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout barbershop-deploy
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DUCKDNS_TOKEN=${{ secrets.DUCKDNS_TOKEN }}
            bash ~/barbershop-deploy/deploy/deploy-all.sh
